//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SierpinskiTriangle.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SierpinskiTriangle.Lang.CoreLang", typeof(CoreLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution.
        /// </summary>
        internal static string MessageBox_Caption_Caution {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBox_Caption_Error {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string MessageBox_Caption_Info {
            get {
                return ResourceManager.GetString("MessageBox_Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an application running..
        /// </summary>
        internal static string MessageBox_Text_App_Already_Running {
            get {
                return ResourceManager.GetString("MessageBox_Text_App_Already_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application for changes to take effect.
        ///
        ///Press OK to exit application..
        /// </summary>
        internal static string MessageBox_Text_Change_Lang_Restart {
            get {
                return ResourceManager.GetString("MessageBox_Text_Change_Lang_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to calculate..
        /// </summary>
        internal static string MessageBox_Text_Error_Calculate {
            get {
                return ResourceManager.GetString("MessageBox_Text_Error_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate..
        /// </summary>
        internal static string MessageBox_Text_Error_Generate {
            get {
                return ResourceManager.GetString("MessageBox_Text_Error_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading user settings.
        ///
        ///Press OK to overwrite old settings..
        /// </summary>
        internal static string MessageBox_Text_Error_Populate_Settings {
            get {
                return ResourceManager.GetString("MessageBox_Text_Error_Populate_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read settings, files may be corrupted..
        /// </summary>
        internal static string MessageBox_Text_Error_Read_Settings {
            get {
                return ResourceManager.GetString("MessageBox_Text_Error_Read_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to cache..
        /// </summary>
        internal static string MessageBox_Text_Error_Save_Cache {
            get {
                return ResourceManager.GetString("MessageBox_Text_Error_Save_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to layout..
        /// </summary>
        internal static string MessageBox_Text_Error_Save_Layout {
            get {
                return ResourceManager.GetString("MessageBox_Text_Error_Save_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to settings..
        /// </summary>
        internal static string MessageBox_Text_Error_Save_Settings {
            get {
                return ResourceManager.GetString("MessageBox_Text_Error_Save_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the application for changes to take effect.
        ///
        ///Press OK to exit application.
        ///Press Cancel to cancel this action..
        /// </summary>
        internal static string MessageBox_Text_Set_Default_Settings {
            get {
                return ResourceManager.GetString("MessageBox_Text_Set_Default_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of levels..
        /// </summary>
        internal static string MessageBox_Text_Warning_Invalid_Num_of_Levels {
            get {
                return ResourceManager.GetString("MessageBox_Text_Warning_Invalid_Num_of_Levels", resourceCulture);
            }
        }
    }
}
